### ISSUE TITLE
Add binary

### ISSUE THREAD

**Issue by Limess** [henriblancke/dbt-formatter#8]
A nice to have is a binary so this package can easily be ran on files using a runner such as [pre-commit](https://pre-commit.com/) or https://github.com/okonet/lint-staged.

e.g. 
```shell
npx dbt-formatter ./path-to-some/file.sql --spaces 2 --indent 2 --sql redshift
```

**Comment by henriblancke** [comment]
Added in #14 (experimental) and part of v1.2.0 release
